# -*- coding: utf-8 -*-
"""Copy of Wikipedia_WebScraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kKWe0CQfilFipV71TI0R3R9LdcX1zkTD
"""

import requests

# Fetch a web page
r = requests.get("https://sw.muet.edu.pk/")
print(r.text)

import re

# Remove HTML tags using RegularExpression
pattern = re.compile(r'<.*?>')  # tags look like <...>
print(pattern.sub('', r.text))  # replace them with blank

from bs4 import BeautifulSoup

# Remove HTML tags using Beautiful Soup library
soup = BeautifulSoup(r.text, "html5lib")
print(soup.get_text())

#mw-content-container
# Find all articles
summaries = soup.find_all("div", class_="hatnote navigation-not-searchable")
summaries[0]

summaries[0].get_text().strip()

